### ISSUE TITLE
Enable semaphore with integration tests

### ISSUE THREAD

**Issue by jcvenegas** [clearcontainers/agent#55] opened 2017-07-18 04:37 UTC
We want to prevent  that our changes does not break clear-containers, lets enable  semaphoreci to run build an image with osbuilder (https://github.com/clearcontainers/osbuilder) and then run integration tests from https://github.com/clearcontainers/tests

**Comment by grahamwhaley** [comment] 2017-07-18 12:59
@jcvenegas @jodh-intel Is this a duplicate of (the admittedly somewhat slim) #25?

**Comment by jodh-intel** [comment] 2017-07-18 13:05
Yep. I'll close the ("wafer thin") #25... :smile:

@jcvenegas - are you planning to work on this, or shall we assign to @sboeuf ?

**Comment by jcvenegas** [comment] 2017-07-18 14:03
@jodh-intel  yes, I am planning to work on this, I dont have powers to assign to me in this repository, could you please add me ?

**Comment by grahamwhaley** [comment] 2017-07-18 14:13
@jcvenegas I've assigned this Issue to you. Do you also need adding to any teams, groups or other settings? Open an Issue if you do.

**Closed as completed** 2017-07-26 05:47 UTC
